package com.bablsoft.accessflow.ai.internal.help;

/**
 * One line of {@code help-corpus/corpus.jsonl} — a single documentation section (or part of one)
 * generated by {@code .github/scripts/build-help-corpus.mjs} (AF-900).
 *
 * <p>{@code text} already opens with a breadcrumb line
 * ({@code AccessFlow Docs > Guides > Run your first governed query > 5. Submit a query}) and is
 * already inside the 800-token budget, so the indexer embeds it verbatim rather than re-splitting it.
 *
 * @param id      content hash, {@code sha256(path + '#' + anchor + ':' + order)[0..16]}
 * @param path    repository-relative source path the chunk was generated from
 * @param url     public documentation URL of the section
 * @param anchor  the heading's {@code id}, or empty when the heading has none
 * @param title   heading text of this chunk's section
 * @param section documentation area label (Guides, Connectors, Reference, …)
 * @param order   part index within the section — counts parts, not sections, so inserting a section
 *                does not renumber the ones after it
 * @param tokens  token count of {@code text} as measured by the generator
 * @param text    the chunk body, breadcrumb line included
 */
public record HelpCorpusChunk(
        String id,
        String path,
        String url,
        String anchor,
        String title,
        String section,
        int order,
        int tokens,
        String text) {
}
