{{- if .Values.autoscaling.frontend.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "accessflow.frontend.fullname" . }}
  labels:
    {{- include "accessflow.frontend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "accessflow.frontend.fullname" . }}
  minReplicas: {{ .Values.autoscaling.frontend.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.frontend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.frontend.targetCPUUtilizationPercentage }}
{{- end }}
