package com.bablsoft.accessflow.notifications.api;

public enum NotificationEventType {
    QUERY_SUBMITTED,
    QUERY_APPROVED,
    QUERY_REJECTED,
    QUERY_ESCALATED,
    REVIEW_TIMEOUT,
    AI_HIGH_RISK,
    ACCESS_REQUEST_SUBMITTED,
    ACCESS_REQUEST_APPROVED,
    ACCESS_REQUEST_REJECTED,
    ACCESS_GRANT_EXPIRED,
    ACCESS_GRANT_REVOKED,
    ANOMALY_DETECTED,
    BREAK_GLASS_EXECUTED,
    WEEKLY_DIGEST,
    ATTESTATION_CAMPAIGN_OPENED,
    API_REQUEST_SUBMITTED,
    API_REQUEST_APPROVED,
    API_REQUEST_EXECUTED,
    API_REQUEST_FAILED,
    API_CONNECTOR_OAUTH2_TOKEN_FAILED,

    ERASURE_APPROVED,

    TEST
}
